#!/bin/bash

# TradingView + Trading System - Quick Commands Reference
# =====================================================

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║      TRADINGVIEW + TRADING SYSTEM - QUICK COMMANDS                ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}INSTALLATION${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Install dependencies"
echo "cd trading_system"
echo "pip3 install -r requirements.txt"
echo ""

echo -e "${BLUE}STARTING THE SYSTEM${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Paper trading with TradingView (safest - start here)"
echo "python3 main_tradingview.py --tradingview --mode paper"
echo ""
echo "# Paper trading with demo alerts (tests system without TradingView)"
echo "python3 main_tradingview.py --tradingview --mode paper --demo"
echo ""
echo "# Custom symbols"
echo "python3 main_tradingview.py --symbols AAPL GOOGL MSFT --tradingview --mode paper"
echo ""
echo "# Custom webhook port"
echo "python3 main_tradingview.py --webhook-port 8000 --tradingview --mode paper"
echo ""
echo "# With authentication token (recommended for production)"
echo "python3 main_tradingview.py --tradingview --webhook-token 'your-secret-key' --mode paper"
echo ""
echo "# LIVE TRADING (⚠️  Real money at risk!)"
echo "python3 main_tradingview.py --tradingview --mode live"
echo ""

echo -e "${BLUE}TESTING${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Check if server is running"
echo "ps aux | grep main_tradingview"
echo ""
echo "# Test webhook endpoint"
echo "curl -X POST http://localhost:5000/webhook/tradingview \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"symbol\":\"AAPL\",\"close\":150.25,\"high\":151,\"low\":149.5,\"open\":149.75,\"volume\":1000000,\"time\":\"2026-03-19\",\"interval\":\"5min\"}'"
echo ""
echo "# Get server status"
echo "curl http://localhost:5000/tradingview/status | python3 -m json.tool"
echo ""
echo "# Get recent candles"
echo "curl http://localhost:5000/tradingview/candles/AAPL?count=20"
echo ""

echo -e "${BLUE}MONITORING${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# View live logs (in another terminal)"
echo "tail -f trading_system.log"
echo ""
echo "# Search logs for specific events"
echo "grep 'Alert received' trading_system.log"
echo "grep 'Entry signal' trading_system.log"
echo "grep 'Trade closed' trading_system.log"
echo ""

echo -e "${BLUE}DATA & RESULTS${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# View closed trades (CSV)"
echo "cat trading_system/data/trades.csv"
echo ""
echo "# View detailed trade data (JSON)"
echo "cat trading_system/data/trades.json | python3 -m json.tool"
echo ""
echo "# View session state"
echo "cat trading_system/data/session.json | python3 -m json.tool"
echo ""

echo -e "${BLUE}BACKTESTING${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Run backtest (verify 51.8% win rate)"
echo "python3 backtest.py"
echo ""

echo -e "${BLUE}DOCUMENTATION${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Quick start (5 min read)"
echo "cat TRADINGVIEW_QUICKSTART.md"
echo ""
echo "# Full setup guide (30 min read)"
echo "cat TRADINGVIEW_SETUP.md"
echo ""
echo "# Complete integration docs"
echo "cat TRADINGVIEW_INTEGRATION.md"
echo ""
echo "# Trading system docs"
echo "cat trading_system/README.md"
echo ""

echo -e "${BLUE}TROUBLESHOOTING${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Check if port 5000 is in use"
echo "lsof -i :5000"
echo ""
echo "# Kill process on port 5000 (if needed)"
echo "lsof -i :5000 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo ""
echo "# View error logs"
echo "tail -100 trading_system.log | grep -i error"
echo ""
echo "# Test connectivity to server"
echo "curl -v http://localhost:5000/tradingview/status"
echo ""

echo -e "${BLUE}ENVIRONMENT${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Find your local IP (for TradingView alerts)"
echo "ifconfig | grep 'inet ' | grep -v 127.0.0.1"
echo ""
echo "# Find your public IP (if using remote server)"
echo "curl ifconfig.me"
echo ""
echo "# Check Python version"
echo "python3 --version"
echo ""
echo "# Check installed packages"
echo "pip3 list"
echo ""

echo -e "${BLUE}DEPLOYMENT${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "# Run as background service (Linux/Mac)"
echo "nohup python3 main_tradingview.py --tradingview --mode paper > server.log 2>&1 &"
echo ""
echo "# Use ngrok for local testing with TradingView"
echo "ngrok http 5000"
echo ""
echo "# Docker run"
echo "docker run -p 5000:5000 trading-system"
echo ""

echo -e "${BLUE}USEFUL TIPS${NC}"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "✓ Always start with PAPER mode to test alerts without real money"
echo "✓ Monitor logs for 1-2 weeks before going live"
echo "✓ Start with just 1 symbol before adding more"
echo "✓ Use authentication token (--webhook-token) in production"
echo "✓ Check server status frequently: curl http://localhost:5000/tradingview/status"
echo "✓ Keep trading_system.log open in another terminal for monitoring"
echo "✓ Read TRADINGVIEW_SETUP.md for detailed troubleshooting"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}                    READY TO TRADE! 🚀${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Next step: python3 main_tradingview.py --tradingview --mode paper"
echo ""
